### ISSUE TITLE
Audio Renderer Error: Please Restart Your Computer

### ISSUE THREAD

**Issue by dtischler** [balenalabs/balena-dash#130]
When using DWB or Hub on a fresh balenaDash install, the device comes online, I set a LAUNCH_URL to a YouTube video, and the kiosk opens up to the YouTube page as it should...however, the video does not play, and instead there is an error in the window, that says: "Audio Renderer Error: Please Restart Your Computer"

This is on a Pi 4.  Has anyone seen this before?

Of note, I manually pushed an old v0.10.2 with a simple `git clone -b v0.10.2 https://github.com/balenalabs/balena-dash/balena-dash.git`, and it worked fine.

**Comment by dtischler** [comment]
![Uploading IMG_2849.JPG…]()

**Comment by superelitist** [comment]
Same hardware, same problem. I'm guessing this is actually a problem with Chromium, but it'd be nice to add a workaround, perhaps as simple as an AUDIO_DISABLE flag.

**Comment by phil-d-wilson** [comment]
This issue has been fixed by removing the ALSA bridge from the V1 version of the browser block. This isn't an issue on the `latest` browser block (e.g. V2) however balenaDash is currently pinned to V1 pending further work.

Users with this issue, should redeploy their balenaDash app, and it will resolve.
